.TH "RTV" "1" "September 06, 2017" "Version 1.18.0" "Usage and Commands"
.SH NAME
RTV - Reddit Terminal Viewer
.SH SYNOPSIS
rtv [\-h] [\-s SUBREDDIT] [\-\-log FILE] [\-\-config FILE] [\-\-ascii] [\-\-monochrome] [\-\-non\-persistent] [\-\-clear\-auth] [\-\-copy\-config] [\-\-copy\-mailcap] [\-\-enable\-media] [\-V] [URL]
.SH DESCRIPTION
Reddit Terminal Viewer is a lightweight browser for https://www.reddit.com
.SH OPTIONS
.TP
\fBURL\fR
[optional] Full URL of a submission to open

.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit

.TP
\fB\-s SUBREDDIT\fR
Name of the subreddit that will be loaded on start

.TP
\fB\-\-log FILE\fR
Log HTTP requests to the given file

.TP
\fB\-\-config FILE\fR
Load configuration settings from the given file

.TP
\fB\-\-ascii\fR
Enable ascii\-only mode

.TP
\fB\-\-monochrome\fR
Disable color

.TP
\fB\-\-non\-persistent\fR
Forget the authenticated user when the program exits

.TP
\fB\-\-clear\-auth\fR
Remove any saved user data before launching

.TP
\fB\-\-copy\-config\fR
Copy the default configuration to {HOME}/.config/rtv/rtv.cfg

.TP
\fB\-\-copy\-mailcap\fR
Copy an example mailcap configuration to {HOME}/.mailcap

.TP
\fB\-\-enable\-media\fR
Open external links using programs defined in the mailcap config

.TP
\fB\-V\fR, \fB\-\-version\fR
show program's version number and exit


.SH CONTROLS
Move the cursor using the arrow keys or vim style movement.
Press \fBup\fR and \fBdown\fR to scroll through submissions.
Press \fBright\fR to view the selected submission and \fBleft\fR to return.
Press \fB?\fR to open the help screen.
.SH FILES
.TP
.BR $XDG_CONFIG_HOME/rtv/rtv.cfg
The configuration file can be used to customize default program settings, see
README.rst for more information.
.TP
.BR $XDG_CONFIG_HOME/rtv/refresh-token
After you login to reddit, your most recent OAuth refresh token will be stored
for future sessions. You can disable this behavior by setting the option
\fBpersistent=False\fR in your configuration file.
.SH ENVIRONMENT
.TP
.BR RTV_EDITOR
Text editor to use when editing comments and submissions. Will fallback to
\fI$EDITOR\fR. 
.TP
.BR RTV_URLVIEWER
Url viewer to use to extract links from comments.  Requires a compatible
program to be installed.
.TP
.BR RTV_BROWSER
Web browser to use when opening links. Will fallback to \fI$BROWSER\fR.
.SH AUTHOR
Michael Lazar <lazar.michael22@gmail.com> (2017).
.SH BUGS
Report bugs to \fIhttps://github.com/michael-lazar/rtv/issues\fR
.SH LICENSE
The MIT License (MIT)
